-- Generated by quickshell/scripts/apply-theme — edit theme.json instead.
return {
    bg_deep = "#0c1218",
    bg_surface = "#141e29",
    bg_overlay = "#212a35",
    bg_inactive = "#28313b",
    fg_main = "#eeeef2",
    fg_muted = "#8d949a",
    fg_subtle = "#60666c",

    rose = "#e279ad",
    pine = "#6486a8",
    love = "#e27979",
    foam = "#8ab7e6",
    gold = "#e2d479",
    iris = "#a579e2",
    subtle_iris = "#7f5fb0",

    deep_pine = "#4e6984",
    vintage_rose = "#e69cc2",
    faded_gold = "#c8c183",
    muted_green = "#7dd29c",
}
