-- Generated by quickshell/scripts/apply-theme — edit theme.json instead.

return {
    active_border   = "rgba(8ab7e68c)",
    inactive_border = "rgba(eeeef21a)",
    shadow          = "rgba(00000066)",
}
