-- Generated by quickshell/scripts/apply-theme — edit theme.json instead.

return {
    active_border   = "rgba(8be9fd8c)",
    inactive_border = "rgba(ffffff1a)",
    shadow          = "rgba(00000066)",
}
